"""
Skill alias dictionary: maps abbreviations/variants to canonical lowercase forms.
"""

# Canonical aliases: raw (lowercase) → canonical form
SKILL_ALIASES = {
    # Programming Languages
    "ml": "machine learning",
    "js": "javascript",
    "ts": "typescript",
    "py": "python",
    "rb": "ruby",
    "c#": "csharp",
    "c sharp": "csharp",
    "c++": "cpp",
    "cplusplus": "cpp",
    "golang": "go",
    "objective c": "objective-c",
    "obj-c": "objective-c",
    "vb.net": "visual basic .net",
    "vb": "visual basic",
    "visual basic 6.0": "visual basic",
    
    # AI/ML
    "deep learning": "deep learning",
    "dl": "deep learning",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "ai": "artificial intelligence",
    "llm": "large language models",
    "llms": "large language models",
    "genai": "generative ai",
    "gen ai": "generative ai",
    "gpt": "gpt",
    "chatgpt": "gpt",
    "reinforcement learning": "reinforcement learning",
    "rl": "reinforcement learning",
    "neural networks": "neural networks",
    "nn": "neural networks",
    "cnn": "convolutional neural networks",
    "rnn": "recurrent neural networks",
    "lstm": "long short-term memory",
    "gan": "generative adversarial networks",
    "transformers": "transformers",
    "bert": "bert",
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "xgboost": "xgboost",
    "lightgbm": "lightgbm",
    "random forest": "random forest",
    "svm": "support vector machines",
    "support vector machine": "support vector machines",
    "linear regression": "linear regression",
    "logistic regression": "logistic regression",
    "decision trees": "decision trees",
    "decision tree": "decision trees",
    
    # Frameworks
    "tf": "tensorflow",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "torch": "pytorch",
    "keras": "keras",
    "react.js": "react",
    "reactjs": "react",
    "react js": "react",
    "react native": "react native",
    "vue.js": "vue",
    "vuejs": "vue",
    "vue js": "vue",
    "angular.js": "angular",
    "angularjs": "angular",
    "angular js": "angular",
    "next.js": "nextjs",
    "nextjs": "nextjs",
    "nuxt.js": "nuxtjs",
    "nuxtjs": "nuxtjs",
    "express.js": "express",
    "expressjs": "express",
    "express js": "express",
    "node.js": "nodejs",
    "nodejs": "nodejs",
    "node js": "nodejs",
    "node": "nodejs",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "fast api": "fastapi",
    "spring boot": "spring boot",
    "springboot": "spring boot",
    "spring": "spring",
    ".net": ".net",
    "dotnet": ".net",
    "asp.net": "asp.net",
    "rails": "ruby on rails",
    "ruby on rails": "ruby on rails",
    "ror": "ruby on rails",
    "laravel": "laravel",
    "svelte": "svelte",
    "jquery": "jquery",
    "bootstrap": "bootstrap",
    "tailwind": "tailwindcss",
    "tailwind css": "tailwindcss",
    "tailwindcss": "tailwindcss",
    "material ui": "material ui",
    "mui": "material ui",
    "selenium": "selenium",
    
    # Databases
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "pg": "postgresql",
    "mysql": "mysql",
    "mongo": "mongodb",
    "mongodb": "mongodb",
    "sql server": "sql server",
    "ms-sql server": "sql server",
    "mssql": "sql server",
    "ms sql": "sql server",
    "ms-sql server / oracle 8/8i": "sql server",
    "sqlite": "sqlite",
    "redis": "redis",
    "dynamodb": "dynamodb",
    "dynamo db": "dynamodb",
    "cassandra": "cassandra",
    "elasticsearch": "elasticsearch",
    "elastic search": "elasticsearch",
    "neo4j": "neo4j",
    "oracle": "oracle",
    "oracle 8/8i": "oracle",
    "mariadb": "mariadb",
    "firebase": "firebase",
    "firestore": "firestore",
    "cosmosdb": "cosmosdb",
    "cosmos db": "cosmosdb",
    "supabase": "supabase",
    
    # Cloud & DevOps
    "aws": "aws",
    "amazon web services": "aws",
    "gcp": "google cloud platform",
    "google cloud": "google cloud platform",
    "azure": "azure",
    "microsoft azure": "azure",
    "k8s": "kubernetes",
    "kubernetes": "kubernetes",
    "docker": "docker",
    "terraform": "terraform",
    "tf (infra)": "terraform",
    "ansible": "ansible",
    "jenkins": "jenkins",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "github actions": "github actions",
    "gitlab ci": "gitlab ci",
    "circle ci": "circleci",
    "circleci": "circleci",
    "devops": "devops",
    "devops / devsecops": "devops",
    "devsecops": "devsecops",
    "helm": "helm",
    "argo cd": "argocd",
    "argocd": "argocd",
    "prometheus": "prometheus",
    "grafana": "grafana",
    "nginx": "nginx",
    "apache": "apache",
    "cloudflare": "cloudflare",
    "vercel": "vercel",
    "netlify": "netlify",
    "heroku": "heroku",
    "digitalocean": "digitalocean",
    "lambda": "aws lambda",
    "aws lambda": "aws lambda",
    "serverless": "serverless",
    "s3": "aws s3",
    "ec2": "aws ec2",
    "ecs": "aws ecs",
    "eks": "aws eks",
    "rds": "aws rds",
    "sqs": "aws sqs",
    "sns": "aws sns",
    "cloudformation": "aws cloudformation",
    
    # Data/Analytics
    "spark": "apache spark",
    "apache spark": "apache spark",
    "pyspark": "pyspark",
    "hadoop": "hadoop",
    "hive": "hive",
    "kafka": "apache kafka",
    "apache kafka": "apache kafka",
    "airflow": "apache airflow",
    "apache airflow": "apache airflow",
    "dbt": "dbt",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "big query": "bigquery",
    "redshift": "redshift",
    "tableau": "tableau",
    "power bi": "power bi",
    "powerbi": "power bi",
    "looker": "looker",
    "etl": "etl",
    "data pipeline": "data pipeline",
    "data engineering": "data engineering",
    "data science": "data science",
    "pandas": "pandas",
    "numpy": "numpy",
    "scipy": "scipy",
    "matplotlib": "matplotlib",
    
    # Tools & Misc
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "bitbucket": "bitbucket",
    "jira": "jira",
    "confluence": "confluence",
    "slack": "slack",
    "figma": "figma",
    "postman": "postman",
    "swagger": "swagger",
    "openapi": "openapi",
    "graphql": "graphql",
    "rest": "rest api",
    "rest api": "rest api",
    "restful": "rest api",
    "grpc": "grpc",
    "websocket": "websocket",
    "websockets": "websocket",
    "oauth": "oauth",
    "jwt": "jwt",
    "json web token": "jwt",
    "linux": "linux",
    "unix": "unix",
    "bash": "bash",
    "powershell": "powershell",
    "vim": "vim",
    "vscode": "vscode",
    "visual studio": "visual studio",
    "intellij": "intellij",
    
    # Testing
    "jest": "jest",
    "mocha": "mocha",
    "chai": "chai",
    "pytest": "pytest",
    "junit": "junit",
    "cypress": "cypress",
    "playwright": "playwright",
    "puppeteer": "puppeteer",
    "tdd": "test driven development",
    "bdd": "behavior driven development",
    "unit testing": "unit testing",
    
    # Methodologies
    "agile": "agile",
    "agile / scrum management": "agile",
    "scrum": "scrum",
    "kanban": "kanban",
    "safe": "safe",
    "safe - agile craft": "safe",
    "lean": "lean",
    "waterfall": "waterfall",
    "microservices": "microservices",
    "micro services": "microservices",
    "design patterns": "design patterns",
    "oop": "object oriented programming",
    "object oriented": "object oriented programming",
    "functional programming": "functional programming",
    "fp": "functional programming",
    "solid": "solid principles",
    "mvc": "mvc",
    "mvvm": "mvvm",
    
    # Mobile
    "ios": "ios",
    "android": "android",
    "flutter": "flutter",
    "dart": "dart",
    "swift": "swift",
    "swiftui": "swiftui",
    "kotlin": "kotlin",
    "xamarin": "xamarin",
    "ionic": "ionic",
    "cordova": "cordova",
    "capacitor": "capacitor",
    
    # Other
    "html": "html",
    "html5": "html",
    "css": "css",
    "css3": "css",
    "sass": "sass",
    "scss": "sass",
    "less": "less",
    "webpack": "webpack",
    "babel": "babel",
    "vite": "vite",
    "parcel": "parcel",
    "npm": "npm",
    "yarn": "yarn",
    "pnpm": "pnpm",
    "typescript": "typescript",
    "php": "php",
    "perl": "perl",
    "scala": "scala",
    "rust": "rust",
    "elixir": "elixir",
    "erlang": "erlang",
    "haskell": "haskell",
    "clojure": "clojure",
    "r": "r",
    "matlab": "matlab",
    "sas": "sas",
    "spss": "spss",
    "stata": "stata",
    "julia": "julia",
    "lua": "lua",
    "assembly": "assembly",
    "solidity": "solidity",
    "blockchain": "blockchain",
    "smart contracts": "smart contracts",
    "web3": "web3",
    "nft": "nft",
    "cybersecurity": "cybersecurity",
    "penetration testing": "penetration testing",
    "pen testing": "penetration testing",
}


def normalize_skill(raw: str) -> str:
    """Normalize a raw skill string to its canonical form."""
    cleaned = raw.strip().lower()
    # Remove trailing periods, commas
    cleaned = cleaned.rstrip(".,;:")
    # Check alias dict
    if cleaned in SKILL_ALIASES:
        return SKILL_ALIASES[cleaned]
    # Default: return cleaned as-is (already lowercase)
    return cleaned


def normalize_skills(raw_list: list[str]) -> list[str]:
    """Normalize a list of raw skill strings, deduplicate, preserve order."""
    seen = set()
    result = []
    for raw in raw_list:
        canonical = normalize_skill(raw)
        if canonical and canonical not in seen:
            seen.add(canonical)
            result.append(canonical)
    return result
